
apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
  namespace: taskmanager-zankovskiy
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "taskmanager_admin"
  MONGO_ROOT_PASSWORD: "lab3-devops-pass"
  MONGO_URI: "mongodb://taskmanager_admin:lab3-devops-pass@mongo:27017/?authSource=admin"
